//
//  PeriodicModel.swift
//  PeriodicTable
//
//  Created by takayuki abe on 2015/02/07.
//  Copyright (c) 2015年 University of Tsukuba. All rights reserved.
//

import UIKit
import RealmSwift

class PeriodicModel: NSObject {
   
    var elements:[Element] = []

    override init() {
        super.init()
        let realm = Realm()
        if realm.objects(Element).count != 83 {
            realm.write{
                realm.deleteAll()
            }

        var empty:Element = Element()
        setElementProperties(empty, symbol: " ", name: "empty", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var one:Element = Element()
        setElementProperties(one,symbol: "1", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var two:Element = Element()
        setElementProperties(two, symbol: "2", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var three:Element = Element()
        setElementProperties(three, symbol: "3", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var four:Element = Element()
        setElementProperties(four, symbol: "4", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var five:Element = Element()
        setElementProperties(five, symbol: "5", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var six:Element = Element()
        setElementProperties(six, symbol: "6", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var seven:Element = Element()
        setElementProperties(seven, symbol: "7", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var eight:Element = Element()
        setElementProperties(eight, symbol: "8", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var nine:Element = Element()
        setElementProperties(nine, symbol: "9", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint: 7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var ten:Element = Element()
        setElementProperties(ten, symbol: "10", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var eleven:Element = Element()
        setElementProperties(eleven, symbol: "11", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var twelve:Element = Element()
        setElementProperties(twelve, symbol: "12", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var thirteen:Element = Element()
        setElementProperties(thirteen, symbol: "13", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var fourteen:Element = Element()
        setElementProperties(fourteen, symbol: "14", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var fifteen:Element = Element()
        setElementProperties(fifteen, symbol: "15", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var sixteen:Element = Element()
        setElementProperties(sixteen, symbol: "16", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var seventeen:Element = Element()
        setElementProperties(seventeen, symbol: "17", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        var eighteen:Element = Element()
        setElementProperties(eighteen, symbol: "18", name: "num", number: 0, massNumber: 0,state:" ", meltingPoint:7000, boilingPoint:7000, ionization:0.0, affinity:0, orbit:" ", category: "")
        
        var H:Element = Element()
        setElementProperties(H,symbol: "H", name: "水素", number: 1, massNumber: 1.008, state: "気体", meltingPoint:-259, boilingPoint:-253, ionization: 1312.0, affinity: 72, orbit: "K1", category: "典型非金属元素")
        var He:Element = Element()
        setElementProperties(He, symbol: "He", name: "ヘリウム", number: 2, massNumber: 4.002, state: "気体", meltingPoint:-272, boilingPoint: -269, ionization: 2372.3, affinity: -48, orbit: "K2", category: "希ガス元素")
        var Li:Element = Element()
        setElementProperties(Li, symbol: "Li", name: "リチウム", number: 3, massNumber: 6.94, state: "個体", meltingPoint: 181, boilingPoint: 1347, ionization: 520.2, affinity: 60, orbit: "K2 L1", category: "アルカリ金属元素")
        var Be:Element = Element()
        setElementProperties(Be, symbol: "Be", name: "ベリリウム", number: 4, massNumber: 9.012, state: "個体", meltingPoint: 1287, boilingPoint: 2472, ionization: 899.5, affinity: 0, orbit: "K2 L2", category: "アルカリ土類金属元素")
        var B:Element = Element()
        setElementProperties(B,symbol: "B", name: "ホウ素", number: 5, massNumber: 10.81, state: "個体", meltingPoint: 2077, boilingPoint: 3870,  ionization: 800.6, affinity: 27, orbit: "K2 L3", category: "典型半金属元素")
        var C:Element = Element()
        setElementProperties(C, symbol: "C", name: "炭素", number: 6, massNumber: 12.011, state: "個体", meltingPoint: 9999, boilingPoint: 3370, ionization: 1086.5, affinity: 122, orbit: "K2 L4", category: "典型非金属元素")
        var N:Element = Element()
        setElementProperties(N, symbol: "N", name: "窒素", number: 7, massNumber: 14.007, state: "気体", meltingPoint: -210, boilingPoint: -196, ionization: 1402.3, affinity: -8, orbit: "K2 L5", category: "典型非金属元素")
        var O:Element = Element()
        setElementProperties(O, symbol: "O", name: "酸素", number: 8, massNumber: 15.999, state: "気体", meltingPoint: -218, boilingPoint: -183, ionization: 1313.9, affinity: 141, orbit: "K2 L6", category: "典型非金属元素")
        var F:Element = Element()
        setElementProperties(F, symbol: "F", name: "フッ素", number: 9, massNumber: 18.998, state: "気体", meltingPoint: -220, boilingPoint: -188, ionization: 1681.0, affinity: 328, orbit: "K2 L7", category: "ハロゲン")
        var Ne:Element = Element()
        setElementProperties(Ne, symbol: "Ne", name: "ネオン", number: 10, massNumber: 20.179, state: "気体", meltingPoint: -249, boilingPoint: -246, ionization: 2080.7, affinity: -116, orbit: "K2 L8", category: "希ガス元素")
        var Na:Element = Element()
        setElementProperties(Na, symbol: "Na", name: "ナトリウム", number: 11, massNumber: 22.989, state: "個体", meltingPoint: 98, boilingPoint: 883, ionization: 495.8, affinity: 53, orbit: "K2 L8 M1", category: "アルカリ金属元素")
        var Mg:Element = Element()
        setElementProperties(Mg, symbol: "Mg", name: "マグネシウム", number: 12, massNumber: 24.305, state: "個体", meltingPoint: 650, boilingPoint: 1095, ionization: 737.7, affinity: 0, orbit: "K2 L8 M2", category: "アルカリ土類金属元素")
        var Al:Element = Element()
        setElementProperties(Al, symbol: "Al", name: "アルミニウム", number: 13, massNumber: 26.981, state: "個体", meltingPoint: 660, boilingPoint: 2520, ionization: 577.5, affinity: 43, orbit: "K2 L8 M3", category: "典型金属元素")
        var Si:Element = Element()
        setElementProperties(Si, symbol: "Si", name: "ケイ素", number: 14, massNumber: 28.085, state: "個体", meltingPoint: 1412, boilingPoint: 3266, ionization: 786.5, affinity: 134, orbit: "K2 L8 M4", category: "典型半金属元素")
        var P:Element = Element()
        setElementProperties(P, symbol: "P", name: "リン", number: 15, massNumber: 30.973, state: "個体", meltingPoint: 590, boilingPoint: 430, ionization: 1011.8, affinity: 72, orbit: "K2 L8 M5", category: "典型非金属元素")
        var S:Element = Element()
        setElementProperties(S, symbol: "S", name: "硫黄", number: 16, massNumber: 32.06, state: "個体", meltingPoint: 113, boilingPoint: 445, ionization: 999.6, affinity: 200, orbit: "K2 L8 M6", category: "典型非金属元素")
        var Cl:Element = Element()
        setElementProperties(Cl, symbol: "Cl", name: "塩素", number: 17, massNumber: 35.45, state: "気体", meltingPoint: -101, boilingPoint: -34, ionization: 1251.2, affinity: 349, orbit: "K2 L8 M7", category: "ハロゲン")
        var Ar:Element = Element()
        setElementProperties(Ar, symbol: "Ar", name: "アルゴン", number: 18, massNumber: 39.948, state: "気体", meltingPoint: -189, boilingPoint: -186, ionization: 1520.6, affinity: -96, orbit: "K2 L8 M8", category: "希ガス元素")
        var K:Element = Element()
        setElementProperties(K, symbol: "K", name: "カリウム", number: 19, massNumber: 39.098, state: "個体", meltingPoint: 64, boilingPoint: 765, ionization: 418.8, affinity: 48, orbit: "K2 L8 M8  N1", category: "アルカリ金属元素")
        var Ca:Element = Element()
        setElementProperties(Ca, symbol: "Ca", name: "カルシウム", number: 20, massNumber: 40.078, state: "個体", meltingPoint: 842, boilingPoint: 1503, ionization: 589.8, affinity: 2, orbit: "K2 L8 M8  N2", category: "アルカリ土類金属元素")
        var Sc:Element = Element()
        setElementProperties(Sc, symbol: "Sc", name: "スカンジウム", number: 21, massNumber: 44.955, state: "個体", meltingPoint: 1539, boilingPoint: 2831, ionization: 633.1, affinity: 18, orbit: "K2 L8 M9 N2", category: "遷移元素")
        var Ti:Element = Element()
        setElementProperties(Ti, symbol: "Ti", name: "チタン", number: 22, massNumber: 47.867, state: "個体", meltingPoint: 1666, boilingPoint: 3289, ionization: 658.8, affinity: 8, orbit: "K2 L8 M10N2", category: "遷移元素")
        var V:Element = Element()
        setElementProperties(V, symbol: "V", name: "バナジウム", number: 23, massNumber: 50.942, state: "個体", meltingPoint: 1917, boilingPoint: 3420, ionization: 650.9, affinity: 51, orbit: "K2 L8 M11N2", category: "遷移元素")
        var Cr:Element = Element()
        setElementProperties(Cr, symbol: "Cr", name: "クロム", number: 24, massNumber: 51.996, state: "個体", meltingPoint: 1857, boilingPoint: 2682, ionization: 652.9, affinity: 65, orbit: "K2 L8 M13N1", category: "遷移元素")
        var Mn:Element = Element()
        setElementProperties(Mn, symbol: "Mn", name: "マンガン", number: 25, massNumber: 54.938, state: "個体", meltingPoint: 1246, boilingPoint: 2062, ionization: 717.3, affinity: 0, orbit: "K2 L8 M13N2", category: "遷移元素")
        var Fe:Element = Element()
        setElementProperties(Fe, symbol: "Fe", name: "鉄", number: 26, massNumber: 55.845, state: "個体", meltingPoint: 1546, boilingPoint: 2863, ionization: 762.5, affinity: 15, orbit: "K2 L8 M14N2", category: "遷移元素")
        var Co = Element()
        setElementProperties(Co, symbol: "Co", name: "コバルト", number: 27, massNumber: 58.933, state: "個体", meltingPoint: 1495, boilingPoint: 2930, ionization: 760.4, affinity: 64, orbit: "K2 L8 M15N2", category: "遷移元素")
        var Ni = Element()
        setElementProperties(Ni, symbol: "Ni", name: "ニッケル", number: 28, massNumber: 58.693, state: "個体", meltingPoint: 1455, boilingPoint: 2890, ionization: 737.1, affinity: 112, orbit: "K2 L8 M16N2", category: "遷移元素")
        var Cu = Element()
        setElementProperties(Cu, symbol: "Cu", name: "銅", number: 29, massNumber: 63.546, state: "個体", meltingPoint: 1085, boilingPoint: 2571, ionization: 745.5, affinity: 119, orbit: "K2 L8 M18N1", category: "遷移元素")
        var Zn = Element()
        setElementProperties(Zn, symbol: "Zn", name: "亜鉛", number: 30, massNumber: 65.38, state: "個体", meltingPoint: 420, boilingPoint: 907, ionization: 906.4, affinity: 0, orbit: "K2 L8 M18N2", category: "遷移元素")
        var Ga = Element()
        setElementProperties(Ga, symbol: "Ga", name: "ガリウム", number: 31, massNumber: 69.723, state: "個体", meltingPoint: 30, boilingPoint: 2208, ionization: 578.8, affinity: 41, orbit: "K2 L8 M18N3", category: "典型金属元素")
        var Ge = Element()
        setElementProperties(Ge, symbol: "Ge", name: "ゲルマニウム", number: 32, massNumber: 72.63, state: "個体", meltingPoint: 937, boilingPoint: 2834, ionization: 762, affinity: 119, orbit: "K2 L8 M18N4", category: "典型半金属元素")
        var As = Element()
        setElementProperties(As, symbol: "As", name: "ヒ素", number: 33, massNumber: 74.921, state: "固定", meltingPoint: 817, boilingPoint: 603, ionization: 947.0, affinity: 79, orbit: "K2 L8 M18N5", category: "典型半金属元素")
        var Se = Element()
        setElementProperties(Se, symbol: "Se", name: "セレン", number: 34, massNumber: 78.971, state: "固定", meltingPoint: 220, boilingPoint: 685, ionization: 941.0, affinity: 195, orbit: "K2 L8 M18N6", category: "典型非金属元素")
        var Br = Element()
        setElementProperties(Br, symbol: "Br", name: "臭素", number: 35, massNumber: 79.904, state: "液体", meltingPoint: -7, boilingPoint: 59, ionization: 1139.9, affinity: 314, orbit: "K2 L8 M18N7", category: "ハロゲン")
        var Kr = Element()
        setElementProperties(Kr, symbol: "Kr", name: "クリプトン", number: 36, massNumber: 83.798, state: "気体", meltingPoint: -157, boilingPoint: -153, ionization: 1350.8, affinity: -96, orbit: "K2 L8 M18N8 ", category: "希ガス元素")
        var Rb = Element()
        setElementProperties(Rb, symbol: "Rb", name: "ルビジウム", number: 37, massNumber: 85.468, state: "個体", meltingPoint: 39, boilingPoint: 688, ionization: 403.0, affinity: 47, orbit: "K2 L8 M18N8 O1", category: "アルカリ金属元素")
        var Sr = Element()
        setElementProperties(Sr, symbol: "Sr", name: "スロトンチウム", number: 38, massNumber: 87.62, state: "個体", meltingPoint: 777, boilingPoint: 1414, ionization: 549.5, affinity: 5, orbit: "K2 L8 M18N8 O2", category: "アルカリ土類金属元素")
        var Y = Element()
        setElementProperties(Y, symbol: "Y", name: "イットリウム", number: 39, massNumber: 88.906, state: "", meltingPoint: 1520, boilingPoint: 3388, ionization: 600, affinity: 30, orbit: "K2 L8 M18N9 O2", category: "遷移元素")
        var Zr = Element()
        setElementProperties(Zr, symbol: "Zr", name:"ジルコニウム", number: 40, massNumber: 91.224, state: "", meltingPoint: 1852, boilingPoint: 4361, ionization: 640.1, affinity: 41, orbit: "K2 L8 M18N10O2", category: "遷移元素")
        var Nb = Element()
        setElementProperties(Nb, symbol: "Nb", name: "ニオブ", number: 41, massNumber: 92.906, state: "", meltingPoint: 2469, boilingPoint: 4927, ionization: 652.1, affinity: 86, orbit: "K2 L8 M18N12O1", category: "遷移元素")
        var Mo = Element()
        setElementProperties(Mo, symbol: "Mo", name: "モリブデン", number: 42, massNumber: 95.95, state: "", meltingPoint: 2623, boilingPoint: 4682, ionization: 684.3, affinity: 72, orbit: "K2 L8 M18N13O1", category: "遷移元素")
        var Tc = Element()
        setElementProperties(Tc, symbol: "Tc", name: "テクネチウム", number: 43, massNumber: 98, state: "", meltingPoint: 2157, boilingPoint: 4265, ionization: 702, affinity: 53, orbit: "K2 L8 M18N13O2", category: "遷移元素")
        var Ru = Element()
        setElementProperties(Ru, symbol: "Ru", name: "ルテニウム", number: 44, massNumber: 101.07, state: "", meltingPoint: 2250, boilingPoint: 4155, ionization: 710.2, affinity: 101, orbit: "K2 L8 M18N15O1", category: "遷移元素")
        var Rh = Element()
        setElementProperties(Rh, symbol: "Rh", name: "ロジウム", number: 45, massNumber: 102.906, state: "", meltingPoint: 1960, boilingPoint: 3697, ionization: 719.7, affinity: 110, orbit: "K2 L8 M18N16O1", category: "遷移元素")
        var Pd = Element()
        setElementProperties(Pd, symbol: "Pd", name: "パラジウム", number: 46, massNumber: 106.42, state: "", meltingPoint: 1552, boilingPoint: 2964, ionization: 804.4, affinity: 54, orbit: "K2 L8 M18N18", category: "遷移元素")
        var Ag = Element()
        setElementProperties(Ag, symbol: "Ag", name: "銀", number: 47, massNumber: 107.868, state: "", meltingPoint: 962, boilingPoint: 2162, ionization: 731.0, affinity: 126, orbit: "K2 L8 M18N18O1", category: "遷移元素")
        var Cd = Element()
        setElementProperties(Cd, symbol: "Cd", name: "カドミウム", number: 48, massNumber: 112.414, state: "", meltingPoint: 321, boilingPoint: 767, ionization: 867.8, affinity: 0, orbit: "K2 L8 M18N18O2", category: "遷移元素")
        var In = Element()
        setElementProperties(In, symbol: "In", name: "インジウム", number: 49, massNumber: 114.818, state: "", meltingPoint: 157, boilingPoint: 2072, ionization: 558.3, affinity: 39, orbit: "K2 L8 M18N18O3", category: "典型金属元素")
        var Sn = Element()
        setElementProperties(Sn, symbol: "Sn", name: "スズ", number: 50, massNumber: 118.710, state: "", meltingPoint: 232, boilingPoint: 2603, ionization: 708.6, affinity: 107, orbit: "K2 L8 M18N18O4", category: "典型金属元素")
        var Sb = Element()
        setElementProperties(Sb, symbol: "Sb", name: "アンチモン", number: 51, massNumber: 121.760, state: "", meltingPoint: 631, boilingPoint: 1587, ionization: 834, affinity: 101, orbit: "K2 L8 M18N18O5", category: "典型半金属元素")
        var Te = Element()
        setElementProperties(Te, symbol: "Te", name: "テルル", number: 52, massNumber: 127.60, state: "", meltingPoint: 450, boilingPoint: 991, ionization: 869.3, affinity: 190, orbit: "K2 L8 M18N18O6", category: "典型半金属元素")
        var I = Element()
        setElementProperties(I, symbol: "I", name: "ヨウ素", number: 53, massNumber: 126.904, state: "", meltingPoint: 114, boilingPoint: 184, ionization: 1008.4, affinity: 295, orbit: "K2 L8 M18N18O7", category: "ハロゲン")
        var Xe = Element()
        setElementProperties(Xe, symbol: "Xe", name: "キセノン", number: 54, massNumber: 131.293, state: "", meltingPoint: -112, boilingPoint: -108, ionization: 1170.4, affinity: -77, orbit: "K2 L8 M18N18O8", category: "希ガス元素")
        var Cs = Element()
        setElementProperties(Cs, symbol: "Cs", name: "セシウム", number: 55, massNumber: 132.905, state: "", meltingPoint: 28, boilingPoint: 658, ionization: 375.7, affinity: 46, orbit: "K2 L8 M18N18O8 P1", category: "アルカリ金属元素")
        var Ba = Element()
        setElementProperties(Ba, symbol: "Ba", name: "バリウム", number: 56, massNumber: 137.327, state: "", meltingPoint: 729, boilingPoint: 1898, ionization: 502.9, affinity: 14, orbit: "K2 L8 M18N18O8 P2", category: "アルカリ土類金属元素")
        var La = Element()
        setElementProperties(La, symbol: "La", name: "ランタン", number: 57, massNumber: 138.905, state: "", meltingPoint: 920, boilingPoint: 3461, ionization: 538.1, affinity: 48, orbit: "K2 L8 M18N18O9 P2", category: "遷移元素")
        var Hf = Element()
        setElementProperties(Hf, symbol: "Hf", name: "ハフニウム", number: 72, massNumber: 178.49, state: "", meltingPoint: 2231, boilingPoint: 4602, ionization: 658.5, affinity: 0, orbit: "K2 L8 M18N31O10P2", category: "遷移元素")
        var Ta = Element()
        setElementProperties(Ta, symbol: "Ta", name: "タンタル", number: 73, massNumber: 180.948, state: "", meltingPoint: 2985, boilingPoint: 5510, ionization: 761, affinity: 31, orbit: "K2 L8 M18N31O11P2", category: "遷移元素")
        var W = Element()
        setElementProperties(W, symbol: "W", name: "タングステン", number: 74, massNumber: 183.84, state: "", meltingPoint: 3407, boilingPoint: 5555, ionization: 770, affinity: 79, orbit: "K2 L8 M18N31O12P2", category: "遷移元素")
        var Re = Element()
        setElementProperties(Re, symbol: "Re", name: "レニウム", number: 75, massNumber: 186.207, state: "", meltingPoint: 3180, boilingPoint: 5596, ionization: 760, affinity: 14, orbit: "K2 L8 M18N31O13P2", category: "遷移元素")
        var Os = Element()
        setElementProperties(Os, symbol: "Os", name: "オスミウム", number: 76, massNumber: 190.23, state: "", meltingPoint: 3045, boilingPoint: 5012, ionization: 840, affinity: 104, orbit: "K2 L8 M18N31O14P2", category: "遷移元素")
        var Ir = Element()
        setElementProperties(Ir, symbol: "Ir", name: "イリジウム", number: 77, massNumber:192.217, state: "", meltingPoint: 2443, boilingPoint: 4437, ionization: 880, affinity: 150, orbit: "K2 L8 M18N31O15P2", category: "遷移元素")
        var Pt = Element()
        setElementProperties(Pt, symbol: "Pt", name: "白金", number: 78, massNumber: 195.084, state: "", meltingPoint: 1769, boilingPoint: 3827, ionization: 870, affinity: 205, orbit: "K2 L8 M18N31O17P1", category: "遷移元素")
        var Au = Element()
        setElementProperties(Au, symbol: "Au", name: "金", number: 79, massNumber: 196.967, state: "", meltingPoint: 1064, boilingPoint: 2857, ionization: 890.1, affinity: 223, orbit: "K2 L8 M18N31O18P1", category: "遷移元素")
        var Hg = Element()
        setElementProperties(Hg, symbol: "Hg", name: "水銀", number: 80, massNumber: 200.59, state: "", meltingPoint: -39, boilingPoint: 357, ionization: 1007.1, affinity: 0, orbit: "K2 L8 M18N31O18P2", category: "遷移元素")
        var Tl = Element()
        setElementProperties(Tl, symbol: "Tl", name: "タリウム", number: 81, massNumber: 204.38, state: "", meltingPoint: 304, boilingPoint: 1473, ionization: 589.4, affinity: 36, orbit: "K2 L8 M18N31O18P3", category: "典型金属元素")
        var Pb = Element()
        setElementProperties(Pb, symbol: "Pb", name: "鉛", number: 82, massNumber: 207.2, state: "", meltingPoint: 328, boilingPoint: 1750, ionization: 715.6, affinity: 35, orbit: "K2 L8 M18N31O18P4", category: "典型金属元素")
        var Bi = Element()
        setElementProperties(Bi, symbol: "Bi", name: "ビスマス", number: 83, massNumber: 208.980, state: "", meltingPoint: 271, boilingPoint: 1561, ionization: 703, affinity: 91, orbit: "K2 L8 M18N31O18P5", category: "典型金属元素")
        var Po = Element()
        setElementProperties(Po, symbol: "Po", name: "ポロニウム", number: 84, massNumber: 209, state: "", meltingPoint: 254, boilingPoint: 962, ionization: 812.1, affinity: 183, orbit: "K2 L8 M18N31O18P6", category: "典型半金属元素")
        var At = Element()
        setElementProperties(At, symbol: "At", name: "アスタチン", number: 85, massNumber: 210, state: "", meltingPoint: 302, boilingPoint: 337, ionization: 890, affinity: 270, orbit: "K2 L8 M18N31O18P7", category: "ハロゲン")
        var Rn = Element()
        setElementProperties(Rn, symbol: "Rn", name: "ラドン", number: 86, massNumber: 222, state: "", meltingPoint: -71, boilingPoint: -62, ionization: 1037, affinity: 0, orbit: "K2 L8 M18N31O18P8", category: "希ガス元素")
        var Fr = Element()
        setElementProperties(Fr, symbol: "Fr", name: "フランシウム", number: 87, massNumber: 223, state: "", meltingPoint: 27, boilingPoint: 677, ionization: 380, affinity: 0, orbit: "K2 L8 M18N31O18P8 Q1", category: "アルカリ金属元素")
        var Ra = Element()
        setElementProperties(Ra,symbol: "Ra", name: "ラジウム", number: 88, massNumber: 226, state: "", meltingPoint: 700, boilingPoint: 1140, ionization: 509.3, affinity: 0, orbit: "K2 L8 M18N31O18P8 Q2", category: "アルカリ土類金属元素")
        var Ac = Element()
        setElementProperties(Ac, symbol: "Ac", name: "アクチニウム", number: 89, massNumber: 227, state: "", meltingPoint: 1050, boilingPoint: 3197, ionization: 499, affinity: 0, orbit: "K2 L8 M18N31O18P9 Q2", category: "遷移元素")

            elements = [empty, one, two, three, four, five, six, seven, H, Li, Na, K, Rb, Cs, Fr, Be, Mg, Ca, Sr, Ba, Ra, Sc, Y, La, Ac, Ti, Zr, Hf, V, Nb, Ta,Cr, Mo, W, Mn, Tc, Re, Fe, Ru, Os, Co, Rh, Ir, Ni, Pd, Pt, Cu, Ag, Au, Zn, Cd, Hg, B, Al, Ga, In, Tl, C, Si, Ge, Sn, Pb, N, P, As, Sb, Bi, O, S, Se, Te, Po, F, Cl, Br, I, At, He, Ne, Ar, Kr, Xe, Rn]
            println(elements.count)
            realm.write {
                for i in 0...elements.count-1 {
                    realm.add(elements[i])
                }
            }
        }
        println(realm.objects(Element))
    }
    func setElementProperties(element: Element, symbol: String, name: String, number: Int, massNumber: Double,state: String, meltingPoint: Int, boilingPoint: Int, ionization: Double, affinity: Int, orbit: String, category: String) {
        element.symbol = symbol
        element.name = name
        element.number = number
        element.massNumber = massNumber
        element.state = state
        element.meltingPoint = meltingPoint
        element.boilingPoint = boilingPoint
        element.ionization = ionization
        element.affinity = affinity
        element.orbit = orbit
        element.category = category
    }
}
